// Build config: src/ (modules) -> dist/index.html (one file). `npm run build` copies it to the root.
// The build must keep the source text: no minify, no tree-shake, no down-level. See DISCOVERY_build.md.
import { defineConfig } from 'vite';
import { viteSingleFile } from 'vite-plugin-singlefile';

const GENERATED = '<!-- GENERATED by `npm run build` from src/. Do not edit this file. Edit src/ and rebuild. -->';

// Marks the built page as generated, right after the doctype.
const markGenerated = {
  name: 'mark-generated',
  transformIndexHtml: { order: 'post', handler: (html) => html.replace(/^<!DOCTYPE html>\n/, `<!DOCTYPE html>\n${GENERATED}\n`) },
};

export default defineConfig({
  root: 'src',
  plugins: [viteSingleFile(), markGenerated],
  build: {
    outDir: '../dist',
    emptyOutDir: true,
    minify: false,
    target: 'esnext',
    modulePreload: false,
    rollupOptions: { treeshake: false },
  },
});
